### ISSUE TITLE
依赖不是 vue2 吗怎么描述是 vue3?

### ISSUE THREAD

**Issue by wll8** [andotorg/electron-vue-app-template#1]
## 依赖
![image](https://user-images.githubusercontent.com/28223260/145398896-8d066d78-359f-48ee-b830-cbb8058cf4ff.png)

## 描述
![image](https://user-images.githubusercontent.com/28223260/145398911-088c1d94-33c0-4b7d-9c18-3b0be7e92884.png)

## 代码
并且初始化也是 vue2 啊？
![image](https://user-images.githubusercontent.com/28223260/145399051-b9b48e81-e3c5-4349-bc6a-41d84888c628.png)

**Comment by andotorg** [comment]
![image](https://user-images.githubusercontent.com/25116294/145528309-e197f1bc-9646-4c5c-9fe8-3ae9eee4ead9.png)

**### Please switch vue3 branch ！**
